version: '3.8'

services:
  nextjs:
    container_name: delpresence-nextjs
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost/api}
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    container_name: delpresence-nginx
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
