version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=delpresence
      - JWT_SECRET=delpresence_secret_key
      - SERVER_PORT=8080
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - delpresence-network
    command: ["/wait-for-it.sh", "db", "5432", "./delpresence-server"]

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delpresence
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delpresence-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  delpresence-network:
    driver: bridge

volumes:
  postgres_data: 