version: '3.8'

services:
  face-recognition-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: delpresence-face-service
    restart: unless-stopped
    ports:
      - "8088:8000"  # Map container port 8000 to host port 8088
    volumes:
      - ./app:/app/app  # Mount app directory for development
      - face_data:/app/face_db  # Persist face database
    environment:
      - DETECTION_MODEL=retinaface  # Detection model to use
      - RECOGNITION_MODEL=ArcFace   # Recognition model to use
      - CONFIDENCE_THRESHOLD=0.6    # Confidence threshold for face detection
      - FACE_DB_DIR=/app/face_db    # Directory to store face embeddings
      - TEMP_DIR=/app/temp          # Directory for temporary files
    networks:
      - delpresence-network

volumes:
  face_data:  # Named volume for face database persistence

networks:
  delpresence-network:
    name: delpresence-network
    external: true  # Use existing network if available, otherwise create it 